# Generated by Django 4.0.3 on 2022-03-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_address_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('NSW', 'NSW'), ('VIC', 'VIC'), ('QLD', 'QLD')], default='NSW', max_length=100),
        ),
    ]
